#!/bin/bash
#---------------edit form here------------------------
url=https://www.jrchintu.workers.dev/1:/ccache.tar.gz
#export build_type="ccache"
#---------------upto here-----------------------------
# Lets see machine specifications and environments
df -h && free -h && nproc && cat /etc/os* && env

if [[ "$build_type" = "ccache" ]];
then
  cd /tmp                               # Where to download cccahe
  time aria2c $url -x16 -s50            # Using aria2c for speed haha, ccache will be at /tmp/ccache.tar.gz since my file name is ccache.tar.gz
  time tar xf ccache.tar.gz             # Extract ccache so ci can use it
  rm -rf ccache.tar.gz                  # Remove unnecessary downloaded file, it will speed up the upload ccache process
else
  echo Build type is non ccache
fi
