#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

#google api
echo "$apicode" >> ./script1.sh && chmod +x ./script1.sh && bash ./script1.sh

repo init -q --no-repo-verify --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# My local manifest can do all clone, and removing or changing repository i need, so lets use it! I am lazy to manually git clone!
git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b debloat .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

#clone device repos
rm -rf device/xiaomi/mido
git clone https://github.com/jrchintu/aex -b debloat device/xiaomi/mido
